# Generated by Django 2.2 on 2022-10-27 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersInfo',
            new_name='TeacherInfo',
        ),
    ]
