# Generated by Django 2.2 on 2022-10-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'Notice'},
        ),
    ]
