# Generated by Django 2.2 on 2022-10-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'StudentInfo'},
        ),
    ]
