# Generated by Django 2.2 on 2022-10-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees_app', '0002_auto_20221024_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name_plural': 'Student Info'},
        ),
    ]
