# Generated by Django 2.2 on 2022-10-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees_app', '0003_auto_20221024_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
