# Generated by Django 2.2 on 2022-10-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_app', '0001_initial'),
        ('school_fees_app', '0004_delete_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeesPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolfees', models.FloatField(null=True)),
                ('when_made', models.DateField(blank=True, null=True)),
                ('debth', models.FloatField(blank=True, null=True)),
                ('troll', models.BooleanField(default=False)),
                ('soap', models.BooleanField(default=False)),
                ('broom', models.BooleanField(default=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.StudentInfo')),
            ],
        ),
    ]
