# Generated by Django 2.2 on 2022-11-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fees_app', '0005_schoolfeespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfeespayment',
            name='debth',
            field=models.FloatField(null=True),
        ),
    ]
