# Generated by Django 2.2 on 2022-10-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.FloatField(blank=True, null=True)),
                ('carpay', models.FloatField(blank=True, null=True)),
                ('schoolfees', models.FloatField(blank=True, null=True)),
                ('when_made', models.DateField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.StudentInfo')),
            ],
        ),
    ]
