# Generated by Django 2.2 on 2022-11-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='carpay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='schoolfees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
