# Generated by Django 2.2 on 2022-11-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_auto_20221110_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='depth',
            field=models.FloatField(null=True),
        ),
    ]
