# Generated by Django 2.2 on 2022-10-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=45, null=True)),
                ('mother', models.CharField(blank=True, max_length=45, null=True)),
                ('father', models.CharField(blank=True, max_length=45, null=True)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('cl', models.CharField(choices=[('F & B', 'F & B'), ('P.S.', 'P.S.'), ('K.S.A.', 'K.S.A.'), ('K.S.B.', 'K.S.B.'), ('K.S.C.', 'K.S.C.'), ('L.S.A.', 'L.S.A.')], max_length=10, null=True)),
                ('residence', models.CharField(choices=[('Dwenem', 'Dwenem'), ('Mpuasu', 'Mpuasu'), ('Adamsu', 'Adamsu'), ('Bodaa', 'Bodaa'), ('Kofitia', 'Kofitia'), ('Adiokor1', 'Adiokor1'), ('Adiokor2', 'Adiokor2'), ('Zezera', 'Zezera'), ('Kwamepim', 'Kwamepim')], max_length=45, null=True)),
                ('fee', models.FloatField(default=210, null=True)),
                ('foodfee', models.FloatField(blank=True, null=True)),
                ('carfee', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('checkifpaiddaily', models.BooleanField(default=False)),
                ('checkifpaidterm', models.BooleanField(default=False)),
                ('debt', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('payment_category', models.CharField(choices=[('Pay_Everything', 'Pay Everything'), ('Dont_Pay', "Don't Pay"), ('Considered', 'Considered')], max_length=40, null=True)),
                ('form_of_transportation', models.CharField(choices=[('Bus', 'Bus'), ('Walk', 'Walk')], max_length=40, null=True)),
                ('payment_method', models.CharField(choices=[('Pay_Per_Day', 'Pay Per Day'), ('School_Fees_Aside', 'School Fees Aside')], max_length=40, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='static/images/passports/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
    ]
