# Generated by Django 2.2 on 2022-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='broom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='soap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='troll',
            field=models.BooleanField(default=False),
        ),
    ]
