# Generated by Django 2.2 on 2022-11-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_auto_20221121_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='debt',
        ),
    ]
