# Generated by Django 2.2 on 2022-11-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_auto_20221123_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='balance',
            new_name='daily_balance',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='debt',
            new_name='daily_debt',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='termly_debt',
            field=models.FloatField(blank=True, default=210, null=True),
        ),
    ]
