# Generated by Django 2.2 on 2023-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_auto_20230304_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='termly_debt',
            field=models.FloatField(blank=True, default=210, null=True),
        ),
    ]
